<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-FNE191SI" ignored="0" name="Default test" tests="6" failures="1" timestamp="19 Nov 2017 07:29:51 GMT" time="25.97" errors="0">
  <testcase name="TC02negativeTest" time="0.006" classname="loginTC.Invalid_gmail_loginverificationCheck"/>
  <testcase name="TC02negativeTest" time="2.464" classname="loginTC.Invalid_gmail_loginverificationCheck"/>
  <testcase name="TC02negativeTest" time="2.385" classname="loginTC.Invalid_gmail_loginverificationCheck"/>
  <testcase name="TC02negativeTest" time="2.417" classname="loginTC.Invalid_gmail_loginverificationCheck"/>
  <testcase name="TC02negativeTest" time="5.217" classname="loginTC.Invalid_gmail_loginverificationCheck"/>
  <testcase name="TC02negativeTest" time="5.09" classname="loginTC.Invalid_gmail_loginverificationCheck">
    <failure type="java.lang.AssertionError" message="Test Case Failed expected [Enter a password] but found [Wrong password. Try again or click Forgot password to reset it.]">
      <![CDATA[java.lang.AssertionError: Test Case Failed expected [Enter a password] but found [Wrong password. Try again or click Forgot password to reset it.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at loginTC.Invalid_gmail_loginverificationCheck.TC02negativeTest(Invalid_gmail_loginverificationCheck.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC02negativeTest -->
</testsuite> <!-- Default test -->
